title: Ayesha Shoaib
avatar: "https://github.com/Ayesha-Shoaib/Ayesha-Shoaib-Portfolio/blob/main/ayesha%20image%202.jpg"
skills:
  - R
  - Python
  - PySpark
  - TensorFlow
  - Workbench
  - SAS
  - Stata
  - Microsoft Power BI
  - Tableau
theme: jekyll-theme-minimal



